---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---
Load and rough clean all data sets
```{r}
setwd("/Applications/Old Computer/Day Lab/Data_Flow")
CD4<-read.csv("CD4.csv")
CD4<-filter(CD4,!(Sample=="Mean"))%>%
filter(!Sample=="StdDev")%>%
filter(!Sample=="Sample")
CD4[CD4=="¥"]<-NA

Cyt<-read.csv("CD4_Cytokine.csv")
Cyt<-filter(Cyt,!(Sample=="Mean"))%>%
filter(!Sample=="StdDev")%>%
filter(!Sample=="Sample")
Cyt[Cyt=="¥"]<-NA

AG<-read.table("/Applications/Old Computer/Day Lab/Data_Flow/CD4_Positive.csv", header= TRUE, sep = ",")
AG<-filter(AG,!(Sample=="Mean"))%>%
filter(!Sample=="StdDev")%>%
filter(!Sample=="Sample")
AG[AG=="¥"]<-NA
AG<-filter(AG,!(Sample=="Mean")) %>%
  filter(!Sample=="StdDev") %>%
  filter(!Sample=="Sample") %>%
  filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")

CYT<-AG[,c(1:18)]
TH1<-AG[,c(1,19:35)]
TH2<-AG[,c(1,53:69)]
TH1.2<-AG[,c(1,36:52)]

write.csv(CD4,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/CD4.csv")
write.csv(Cyt,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cytokine.csv")
write.csv(CYT,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cyt.csv")
write.csv(TH1,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1.csv")
write.csv(TH2,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH2.csv")
write.csv(TH1.2,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1-2.csv")

remove(AG, CD4, Cyt, CYT, TH1, TH2, TH1.2)
```

PBMC
```{r}
PBMC<-read.csv("/Applications/Old computer/Day Lab/Data_Flow/PBMC.csv")
PBMC<-filter(PBMC,!(Helminth.Status=="Ascaris+"))%>%
        filter(!Helminth.Status=="Ascarus+ & Trichuris+")%>%
        filter(!(Helminth.Status=="Hookworm+"))%>%
        filter(!(Helminth.Status=="Trichuris+"))
PBMC$TB.Status = factor(PBMC$TB.Status,levels=c("Healthy Control", "LTBI", "Active TB"))
```

cleaning total CD4 data
```{r}
## Names Labels Etc. for X and SM
#remember to check for _ issues
setwd("/Applications/Old Computer/Day Lab/Data_Flow/Clean")
CD4<-read.csv("CD4.csv")

CD4<-filter(CD4,!(Sample=="Mean")) %>%
  filter(!Sample=="StdDev") %>%
  filter(!Sample=="Sample") %>%
  filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")


Split<-strsplit(as.character(CD4$Sample),"_");
CD4$Donor = as.factor(sapply(Split,"[",1));
CD4$TB = as.factor(sapply(Split,"[",2));
CD4$SM = as.factor(sapply(Split,"[",3));
CD4$Antigen = as.factor(sapply(Split,"[",4));

CD4<-as.data.table(CD4)
CD4<-CD4[CD4$SM!="HEL"]

CD4$SM<-factor(CD4$SM, levels=c("N","X","SM"))
CD4$TB<-factor(CD4$TB, levels=c("N","HC", "LTBI", "TB"))
CD4$Stim = factor(CD4$Antigen,levels=c("UN", "WCL","PEP","SEA", "SWAP", "PMA"))
CD4<-CD4[!(is.na(CD4$Sample))]

write.csv(CD4,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/CD4.csv")
```
cleaning cytokine frequency data
```{r}
Cyt<-read.csv("/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cytokine.csv")

Cyt<-filter(Cyt,!(Sample=="Mean")) %>%
  filter(!Sample=="StdDev") %>%
  filter(!Sample=="Sample") %>%
  filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")


Split<-strsplit(as.character(Cyt$Sample),"_");
Cyt$Donor = as.factor(sapply(Split,"[",1));
Cyt$TB = as.factor(sapply(Split,"[",2));
Cyt$SM = as.factor(sapply(Split,"[",3))
Cyt$Antigen = as.factor(sapply(Split,"[",4));

Cyt<-as.data.table(Cyt)
Cyt<-Cyt[Cyt$SM!="HEL"]

Cyt$SM<-factor(Cyt$SM, levels=c("N","X","SM"))
Cyt$TB<-factor(Cyt$TB, levels=c("N","HC", "LTBI", "TB"))
Cyt$Stim = factor(Cyt$Antigen,levels=c("UN", "WCL","PEP","SEA", "SWAP", "PMA"))

Cyt<-Cyt[!(is.na(Cyt$Sample))]
remove(Split)
write.csv(Cyt,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cytokine.csv")

```

Determining antigen specific threshold vlaues
```{r}
UN<-filter(Cyt,Stim=="UN")
ag<-filter(Cyt,Stim!="UN")
ag[ag<0.03]<-NA
Dat<-merge(ag,UN,by="Donor")
Dat<-as.data.table(Dat)

Dat$Sample<-Dat$Sample.x
Dat$Stim<-Dat$Stim.x
Dat$TB<-Dat$TB.x
Dat$SM<-Dat$SM.x
Dat$G_4_13_T<-(Dat$G_4_13_T.x-3*Dat$G_4_13_T.y)
Dat$G_4_13_x<-(Dat$G_4_13_x.x-3*Dat$G_4_13_x.y)
Dat$G_4_x_T<-(Dat$G_4_x_T.x-3*Dat$G_4_x_T.y)
Dat$G_4_x_x<-(Dat$G_4_x_x.x-3*Dat$G_4_x_x.y)
Dat$G_x_13_T<-(Dat$G_x_13_T.x-3*Dat$G_x_13_T.y)
Dat$G_x_13_x<-(Dat$G_x_13_x.x-3*Dat$G_x_13_x.y)
Dat$G_x_x_T<-(Dat$G_x_x_T.x-3*Dat$G_x_x_T.y)
Dat$G_x_x_x<-(Dat$G_x_x_x.x-3*Dat$G_x_x_x.y)
Dat$x_4_13_T<-(Dat$x_4_13_T.x-3*Dat$x_4_13_T.y)
Dat$x_4_13_x<-(Dat$x_4_13_x.x-3*Dat$x_4_13_x.y)
Dat$x_4_x_T<-(Dat$x_4_x_T.x-3*Dat$x_4_x_T.y)
Dat$x_4_x_x<-(Dat$x_4_x_x.x-3*Dat$x_4_x_x.y)
Dat$x_x_13_T<-(Dat$x_x_13_T.x-3*Dat$x_x_13_T.y)
Dat$x_x_13_x<-(Dat$x_x_13_x.x-3*Dat$x_x_13_x.y)
Dat$x_x_x_T<-(Dat$x_x_x_T.x-3*Dat$x_x_x_T.y)
Dat$x_x_x_x<-Dat$x_x_x_x.x
Dat$IFNg<-(Dat$IFNg.x-3*Dat$IFNg.y)
Dat$IL13<-(Dat$IL13.x-3*Dat$IL13.y)
Dat$IL4<-(Dat$IL4.x-3*Dat$IL4.y)
Dat$TNFa<-(Dat$TNFa.x-3*Dat$TNFa.y)
Dat$Cyt.Count<-(Dat$Cyt.Count.x-3*Dat$Cyt.Count.y)
Dat$Cyt.Freq<-(Dat$Cyt.Freq.x-3*Dat$Cyt.Freq.y)
Dat$TH1.Count<-(Dat$TH1.Count.x-3*Dat$TH1.Count.y)
Dat$TH1.Freq<-(Dat$Th1.Freq.x-3*Dat$Th1.Freq.y)
Dat$TH1.2.Count<-(Dat$TH1.2.Count.x-3*Dat$TH1.2.Count.y)
Dat$TH1.2.Freq<-(Dat$TH1.2.Freq.x-3*Dat$TH1.2.Freq.y)
Dat$TH2.Count<-(Dat$TH2.Count.x-3*Dat$TH2.Count.y)
Dat$TH2.Freq<-(Dat$TH2.Freq.x-3*Dat$TH2.Freq.y)

AG<-Dat[,c(1,70:88,90:93,95,97,99,101)]

AG[AG <0 ]<-as.numeric(0)
AG[AG >0 ]<-as.numeric(1)

AG$Sum<-rowSums(AG[,6:28], na.rm=TRUE)
AG$Cyt.Sum<-rowSums(AG[,21:24], na.rm = TRUE)
AG$TH1.Sum<-rowSums(AG[,c(12,13,20,21,24,26)], na.rm = TRUE)
AG$TH2.Sum<-rowSums(AG[,c(15,17,19,22,23,28)], na.rm = TRUE)
AG$TH1.2.Sum<-rowSums(AG[,c(6:11,14,16,18,27)], na.rm = TRUE)

x <- split(AG, AG$Stim)

c<-lapply(x, function(g) colSums(g[,6:28], na.rm = TRUE))
c2<-as.data.table(c)
c3<-cbind(names(AG))
cyt.tally<-cbind(c3[6:28],c2)

r<-lapply(x, function(g) rowSums(g[,6:28], na.rm = TRUE))
r2<-as.data.table(r)
r3<-unique(cbind(as.character(AG$Donor)))
donor.tally<-cbind(r3,r2)

remove(UN, ag, Dat, c, c2, c3, r, r2, r3, x)
write.csv(cyt.tally,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/cyt-tally.csv")
write.csv(donor.tally,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/donor-tally.csv")
write.csv(AG,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/threshold-data.csv")

```

Background subtracting cytokine frequencies
```{r}
UN<-filter(Cyt,Stim=="UN")
ag<-filter(Cyt,Stim!="UN")
Dat<-merge(ag,UN,by="Donor")
Dat<-as.data.table(Dat)

Dat$Sample<-Dat$Sample.x
Dat$Stim<-Dat$Stim.x
Dat$TB<-Dat$TB.x
Dat$SM<-Dat$SM.x
Dat$G_4_13_T<-(Dat$G_4_13_T.x-Dat$G_4_13_T.y)
Dat$G_4_13_x<-(Dat$G_4_13_x.x-Dat$G_4_13_x.y)
Dat$G_4_x_T<-(Dat$G_4_x_T.x-Dat$G_4_x_T.y)
Dat$G_4_x_x<-(Dat$G_4_x_x.x-Dat$G_4_x_x.y)
Dat$G_x_13_T<-(Dat$G_x_13_T.x-Dat$G_x_13_T.y)
Dat$G_x_13_x<-(Dat$G_x_13_x.x-Dat$G_x_13_x.y)
Dat$G_x_x_T<-(Dat$G_x_x_T.x-Dat$G_x_x_T.y)
Dat$G_x_x_x<-(Dat$G_x_x_x.x-Dat$G_x_x_x.y)
Dat$x_4_13_T<-(Dat$x_4_13_T.x-Dat$x_4_13_T.y)
Dat$x_4_13_x<-(Dat$x_4_13_x.x-Dat$x_4_13_x.y)
Dat$x_4_x_T<-(Dat$x_4_x_T.x-Dat$x_4_x_T.y)
Dat$x_4_x_x<-(Dat$x_4_x_x.x-Dat$x_4_x_x.y)
Dat$x_x_13_T<-(Dat$x_x_13_T.x-Dat$x_x_13_T.y)
Dat$x_x_13_x<-(Dat$x_x_13_x.x-Dat$x_x_13_x.y)
Dat$x_x_x_T<-(Dat$x_x_x_T.x-Dat$x_x_x_T.y)
Dat$x_x_x_x<-Dat$x_x_x_x.x
Dat$IFNg<-(Dat$IFNg.x-Dat$IFNg.y)
Dat$IL13<-(Dat$IL13.x-Dat$IL13.y)
Dat$IL4<-(Dat$IL4.x-Dat$IL4.y)
Dat$TNFa<-(Dat$TNFa.x-Dat$TNFa.y)
Dat$Cyt.Count<-(Dat$Cyt.Count.x-Dat$Cyt.Count.y)
Dat$Cyt.Freq<-(Dat$Cyt.Freq.x-Dat$Cyt.Freq.y)
Dat$TH1.Count<-(Dat$TH1.Count.x-Dat$TH1.Count.y)
Dat$TH1.Freq<-(Dat$Th1.Freq.x-Dat$Th1.Freq.y)
Dat$TH1.2.Count<-(Dat$TH1.2.Count.x-Dat$TH1.2.Count.y)
Dat$TH1.2.Freq<-(Dat$TH1.2.Freq.x-Dat$TH1.2.Freq.y)
Dat$TH2.Count<-(Dat$TH2.Count.x-Dat$TH2.Count.y)
Dat$TH2.Freq<-(Dat$TH2.Freq.x-Dat$TH2.Freq.y)

CYT<-Dat[,c(1,70:101)]
CYT[CYT<0]<-0
remove(UN, ag, Dat, Cyt)

write.csv(CYT,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/Background Subtracted Cytokine.csv")
```

#Antigen specific responses using threshold values
```{r}
Cyt<-read.csv("/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cyt.csv")
TH1<-read.csv("/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1.csv")
TH2<-read.csv("/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH2.csv")
TH1.2<-read.csv("/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1-2.csv")

TH1<-merge(AG,TH1,by="Sample", all=TRUE)
TH2<-merge(AG,TH2,by="Sample", all=TRUE)
TH1.2<-merge(AG,TH1.2,by="Sample", all=TRUE)
Cyt<-merge(AG,Cyt,by="Sample", all=TRUE)

Cyt<-Cyt[,c(1,3:5,21:25,29,30,35:51)]
TH1<-TH1[,c(1:5,21,24,26,31,35:51)]
TH2<-TH2[,c(1:5,22:23,28,32,35:51)]
TH1.2<-TH1.2[,c(1:5,21:24,27,33,35:51)]

write.csv(Cyt,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/Cyt_pos.csv")
write.csv(TH1,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1_pos.csv")
write.csv(TH2,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH2_pos.csv")
write.csv(TH1.2,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/TH1-2_pos.csv")
```

Load and rough clean all counts sets
```{r}
setwd("/Applications/Old Computer/Day Lab/Data_Flow")
CD4_count<-read.csv("CD4_counts.csv")
CD4_count<-filter(CD4_count,!(Sample=="Mean"))%>%
    filter(!Sample=="StdDev")%>%
    filter(!Sample=="Sample")%>%
    filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
    filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")
CD4_count[CD4_count=="¥"]<-NA

Split<-strsplit(as.character(CD4_count$Sample),"_");
CD4_count$ID = as.factor(sapply(Split,"[",1));
CD4_count$TB = as.factor(sapply(Split,"[",2));
CD4_count$SM = as.factor(sapply(Split,"[",3));
CD4_count$Antigen = as.factor(sapply(Split,"[",4));
CD4_count$cell<-"CD4"

CD4_count<-as.data.table(CD4_count)
CD4_count<-CD4_count[CD4_count$SM!="HEL"]

CD4_count$SM<-factor(CD4_count$SM, levels=c("N","X","SM"))
CD4_count$TB<-factor(CD4_count$TB, levels=c("N","HC", "LTBI", "TB"))
CD4_count$Stim = factor(CD4_count$Antigen,levels=c("UN", "WCL","PEP","SEA", "SWAP", "PMA"))
CD4_count<-CD4_count[!(is.na(CD4_count$Sample))]

write.csv(CD4_count,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/CD4_count.csv")

CD8<-read.csv("CD8_counts.csv")
CD8<-filter(CD8,!(Sample=="Mean"))%>%
filter(!Sample=="StdDev")%>%
filter(!Sample=="Sample")%>%
    filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")
CD8[CD8=="¥"]<-NA

Split<-strsplit(as.character(CD8$Sample),"_");
CD8$ID = as.factor(sapply(Split,"[",1));
CD8$TB = as.factor(sapply(Split,"[",2));
CD8$SM = as.factor(sapply(Split,"[",3));
CD8$Antigen = as.factor(sapply(Split,"[",4));
CD8$cell<-"CD8"

CD8<-as.data.table(CD8)
CD8<-CD8[CD8$SM!="HEL"]

CD8$SM<-factor(CD8$SM, levels=c("N","X","SM"))
CD8$TB<-factor(CD8$TB, levels=c("N","HC", "LTBI", "TB"))
CD8$Stim = factor(CD8$Antigen,levels=c("UN", "WCL","PEP","SEA", "SWAP", "PMA"))
CD8<-CD8[!(is.na(CD8$Sample))]

write.csv(CD8,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/CD8_count.csv")


GD<-read.csv("GD_counts.csv")
GD<-filter(GD,!(Sample=="Mean"))%>%
filter(!Sample=="StdDev")%>%
filter(!Sample=="Sample")%>%
    filter(!Sample=="NK2126_HC_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2450_HC_SM_SEA_047.fcs") %>%
  filter(!Sample=="NK2402_LTBI_SM_SWAP_024.fcs") %>%
  filter(!Sample=="NK2342_TB_X_SWAP_006.fcs") %>%
  filter(!Sample=="NK2136_TB_X_WCL_003.fcs") %>%
  filter(!Sample=="NK2168_HC_SM_WCL_040.fcs") %>%
  filter(!Sample=="NK2421_LTBI_SM_PEP_010.fcs") %>%
  filter(!Sample=="NK2063_TB_X_SEA_005.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_PEP_010.fcs") %>%
  filter(!Sample=="NK2115_LTBI_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2171_HC_X_WCL_009.fcs") %>%
  filter(!Sample=="NK2162_HC_X_SEA_023.fcs")
GD[GD=="¥"]<-NA

Split<-strsplit(as.character(GD$Sample),"_");
GD$ID = as.factor(sapply(Split,"[",1));
GD$TB = as.factor(sapply(Split,"[",2));
GD$SM = as.factor(sapply(Split,"[",3));
GD$Antigen = as.factor(sapply(Split,"[",4));
GD$cell<-"GD"

GD<-as.data.table(GD)
GD<-GD[GD$SM!="HEL"]

GD$SM<-factor(GD$SM, levels=c("N","X","SM"))
GD$TB<-factor(GD$TB, levels=c("N","HC", "LTBI", "TB"))
GD$Stim = factor(GD$Antigen,levels=c("UN", "WCL","PEP","SEA", "SWAP", "PMA"))
GD<-GD[!(is.na(GD$Sample))]

write.csv(GD,"/Applications/Old Computer/Day Lab/Data_Flow/Clean/GD_count.csv")

```



