---
title: "Committee Meeting 2017"
output:
  pdf_document: default
  html_notebook: default
---
setwd("/Users/oldmac/Desktop/Day Lab/Data")

```{r}
FP<- read.csv("Fix Perm.csv")
splStudyID = strsplit(as.character(FP$Sample),":");
FP$Sample = as.factor(sapply(splStudyID,"[",2));
splStudyID = strsplit(as.character(FP$Sample),"_");
FP$Donor = as.factor(sapply(splStudyID,"[",1));
FP$Antigen = as.factor(sapply(splStudyID,"[",2));
FP$FP = as.factor(sapply(splStudyID,"[",3));
FP$Stim = factor(FP$Antigen,levels=c("UN", "WCL","Pep","PMA"))
FP$Condition <- as.character("Frozen")
```

```{r}
Fresh<-read.csv("Fresh.csv")
splStudyID = strsplit(as.character(Fresh$Sample),":");
Fresh$Sample = as.factor(sapply(splStudyID,"[",2));
splStudyID = strsplit(as.character(Fresh$Sample),"_");
Fresh$Donor = as.factor(sapply(splStudyID,"[",1));
Fresh$Antigen = as.factor(sapply(splStudyID,"[",2));
Fresh$Stim = factor(Fresh$Antigen,levels=c("UN", "WCL","Pep","PMA"))
Fresh$Condition <- as.character("Fresh")
```

```{r}
Frozen<-read.csv("Frozen.csv")
splStudyID = strsplit(as.character(Frozen$Sample),":");
Frozen$Sample = as.factor(sapply(splStudyID,"[",2));
splStudyID = strsplit(as.character(Frozen$Sample),"_");
Frozen$Donor = as.factor(sapply(splStudyID,"[",1));
Frozen$Antigen = as.factor(sapply(splStudyID,"[",2));
Frozen$Stim = factor(Frozen$Antigen,levels=c("UN", "WCL","Pep","PMA"))
Frozen$FP = as.factor(sapply(splStudyID,"[",3));
Frozen$Condition <- as.character("Frozen")
```

```{r}
TB<-rbind.fill(Fresh,Frozen)
TB<-data.table(TB)
TB<-TB[!(Stim=="PMA")]
```

```{r}
pd <- position_dodge(width=0.5)  

ggplot(TB, aes(x=Stim, y=CD4.TH1, color=FP)) + 
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH1 Cytokine+ CD4+ T cells") +
  ggtitle("TH1") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

```{r}
ggplot(TB, aes(x=Stim, y=CD4.TH1.2, color=FP)) + 
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH1/2 Cytokine+ CD4+ T cells") +
  ggtitle("TH1/TH2") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

```{r}
ggplot(TB, aes(x=Stim, y=CD4.TH2, color=FP)) + 
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH2 Cytokine+ CD4+ T cells") +
  ggtitle("TH2") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
```

```{r}
Dat1<-summarySE(FP, measurevar="CD4.TH1", groupvars=c("Stim","FP"))
ggplot(Dat1, aes(x=Stim, y=CD4.TH1, color=FP)) + 
  geom_errorbar(aes(ymin=CD4.TH1-se, ymax=CD4.TH1+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH1 Cytokine+ CD4+ T cells") +
  ggtitle("TH1") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

```{r}
Dat2<-summarySE(FP, measurevar="CD4.TH1.2", groupvars=c("Stim","FP"))
ggplot(Dat2, aes(x=Stim, y=CD4.TH1.2, color=FP)) + 
  geom_errorbar(aes(ymin=CD4.TH1.2-se, ymax=CD4.TH1.2+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH1/2 Cytokine+ CD4+ T cells") +
  ggtitle("TH1/TH2") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

```{r}
Dat3<-summarySE(FP, measurevar="CD4.TH2", groupvars=c("Stim","FP"))
ggplot(Dat3, aes(x=Stim, y=CD4.TH2, color=FP)) + 
  geom_errorbar(aes(ymin=CD4.TH2-se, ymax=CD4.TH2+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  geom_point(position=pd, size=10) +
  xlab("Stimulation") +
  ylab("% TH2 Cytokine+ CD4+ T cells") +
  ggtitle("TH2") +
  theme_bw()+
  theme(text = element_text(size = 30))+
  theme(legend.position="bottom")
```

