---
title: "Graphs"
output: html_document
---
http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
library(RColorBrewer)
display.brewer.all()
http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html


#67001f dark red
#b2182b red
#d1e5f0 light blue
#2166ac dark blue
#1a9850 green
#91cf60 light green


```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
```

```{r}
dodge <- position_dodge(width = 1)
Infection=c("#9e9e9e","#900C3F", "#1E88E5")
Helper=c("#C86CC2","#3787CE","#000A61")
Palette=c( "#1E88E5", "#900C3F")
Q<-c("#009999","#663399","#CC0066")
```

boolean
```{r setup, include=FALSE}
#HC
HC<-subset(melt, TB %in% "HC")
g<-ggplot(HC, aes(x=label, y=value, color=SM))

g +
  xlab("") +
  ylab("Frequency Cytokine+ CD4+ T-cells (%)") +
  ggtitle("HC") +
  geom_boxplot(outlier.shape = NA, size=1.8, position=dodge)+
  scale_color_manual((values=Infection), name="Helminth Status")+
  theme_bw()+
  theme(axis.text=element_text(size=20,face="bold"),axis.title=element_text(size=24,face="bold"),plot.title=element_text(size=30,face="bold"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.key.size = unit(2.5, "cm"))+
  theme(legend.text = element_text(size = 20))

```

TB groups +/- SM for whatever
```{r}
data<-CYT[Stim=="WCL"]
data<-subset(CYT,CYT$Stim=="PMA")
g <- ggplot(data, aes(x=SM, y=Cyt.Freq, color=SM))

g + geom_boxplot(outlier.shape = NA, size=1) + 
        geom_jitter(width=.1,height=0, shape=1,size=2) +
        scale_color_manual(labels = c("SM(-)", "SM(+)"), values = Palette) +
        scale_x_discrete(breaks=c("X","SM"),
                           labels=c("SM(-)", "SM(+)"))+
        theme_bw()+
        theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
        facet_wrap(~TB,nrow = 1, scale="free_x")+
        labs(title="Cytokine Frequencies", 
             subtitle="",
             caption="",
             x="TB and Helminth Status",
             y="Frequency of Cytokine+ CD4+ T cells")


#
geom_boxplot(outlier.shape = NA, size=2, position=dodge)+
coord_cartesian(ylim=c(0,100))+

        
theme(legend.key.size = unit(2.5, "cm"))+
theme(legend.text = element_text(size = 20))+
theme_bw()+
theme(plot.title = element_text(hjust = 0.5))+
theme(axis.text=element_text(size=16),axis.title=element_text(size=20,face="bold"),plot.title=element_text(size=24,face="bold"))+
theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())+    

```

Ways to save images
```{r}
jpeg("jpeg", width = 15, height = 9, units = 'in', res = 300)
###plot
dev.off()

tiff('tiff', units="in", width=15, height=9, res=300, compression = 'lzw')
###plot
dev.off()

png("png", width = 15, height = 9, units = 'in', res = 300)
###plot
dev.off()
```

pie charts
```{r}
pie(tf$mean[tf$TB=="TB" & tf$SM=="SM"],labels=tf$variable, col=Palette)
pie(tf$mean[tf$TB=="LTBI" & tf$SM=="SM"],labels=tf$variable, col=Palette)
pie(tf$mean[tf$TB=="HC" & tf$SM=="SM"],labels=tf$variable, col=Palette)
pie(tf$mean[tf$TB=="TB" & tf$SM=="X"],labels=tf$variable, col=Palette)
pie(tf$mean[tf$TB=="LTBI" & tf$SM=="X"],labels=tf$variable, col=Palette)
pie(tf$mean[tf$TB=="HC" & tf$SM=="X"],labels=tf$variable, col=Palette)

pie(cc$mean[cc$TB=="TB" & cc$SM=="SM"],labels=cc$variable, col=Palette)
pie(cc$mean[cc$TB=="LTBI" & cc$SM=="SM"],labels=cc$variable, col=Palette)
pie(cc$mean[cc$TB=="HC" & cc$SM=="SM"],labels=cc$variable, col=Palette)
pie(cc$mean[cc$TB=="TB" & cc$SM=="X"],labels=cc$variable, col=Palette)
pie(cc$mean[cc$TB=="LTBI" & cc$SM=="X"],labels=cc$variable, col=Palette)
pie(cc$mean[cc$TB=="HC" & cc$SM=="X"],labels=cc$variable, col=Palette)
```


prep for a stacked bar
```{r}
df<-PMA[,c(4,5,27:34)]
df$TH1.Portion<-(df$TH1.Count/df$Cyt.Count)
df$TH2.Portion<-(df$TH2.Count/df$Cyt.Count)
df$TH1.2.Portion<-(df$TH1.2.Count/df$Cyt.Count)
df$TH1.Port<-(df$TH1.Freq/df$Cyt.Freq)
df$TH2.Port<-(df$TH2.Freq/df$Cyt.Freq)
df$TH1.2.Port<-(df$TH1.2.Freq/df$Cyt.Freq)

#unscaled frequencies
df1<-df[,c(1,2,6,8,10)]
df2<-melt(df1,id.vars=c("TB","SM"))
df3<-as.data.frame(
  ddply(df2, c("TB", "SM", "variable"), summarise,
        median = median(value), sd = sd(value),
        error = qnorm(0.975)*sd(value)/sqrt(length(value))))
df3$upper<-(df3$median+df3$error)
df3$lower<-(df3$median-df3$error)

df3$variable<-factor(df3$variable, levels=c('TH2.Freq','TH1.2.Freq','TH1.Freq',ordered=TRUE))
df3$Label <- paste(df3$TB, df3$SM, sep='_')
```

unscaled stacked bar
```{r}
g<-ggplot(df3, aes(SM, median))

g+ geom_bar(aes(fill = factor(variable)), stat="identity", width = 0.7) +
  scale_colour_brewer(palette = "Helper")+
  facet_wrap(~TB,nrow = 1)+
  geom_errorbar(aes(ymax=upper , ymin= lower ),width=.5) +
  theme(panel.background = element_rect(fill='white', colour='white'), 
        panel.grid = element_line(color = NA),
        panel.grid.minor = element_line(color = NA),
        panel.border = element_rect(fill = NA, color = "black"),
        axis.text.x  = element_text(size=10, colour="black", face = "bold"), 
        axis.title.x = element_text(vjust=0.1, face = "bold"),
        axis.text.y = element_text(size=12, colour="black"),
        axis.title.y = element_text(vjust=0.2, size = 12, face = "bold"))

```

