---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE )
```

```{r Donor Info}
library(dplyr)
setwd("/Applications/Old Computer/Day Lab/Flow-Data/exported")
PBMC<-read.csv("ICS_PBMC.csv")
PBMC<-dplyr::filter(PBMC, Helminth.Status=="Schisto+" | Helminth.Status== "Negative" | Helminth.Status== "Not US" | Helminth.Status=="US" | Helminth.Status== "Unknown")
PBMC$TB.Status = factor(PBMC$TB.Status,levels=c("Naïve","BCG","Healthy Control", "LTBI", "Active TB", "Unknown"))
PBMC$Viability <- gsub("%/%" , "", PBMC$Viability)
PBMC$Exp.Date <- gsub("TM", "", PBMC$Exp.Date)
PBMC<- dplyr::filter(PBMC, !(Excluded=="EX"))%>%
    dplyr::rename(TB = TB.Status, SM = Helminth.Status, StudyID = Study.ID)%>%
    dplyr::select(StudyID, TB, SM, Viability, Cells.Vial, Excluded)

QFT<- read.csv("/Applications/Old Computer/Epi Project/Data_clean/complete-kenya.csv")
QFT<- dplyr::filter(QFT, StudyID %in% PBMC$StudyID)%>%
    dplyr::select(StudyID, age, sex, QFT, SchistosomaIntensity)
QFTStudyID<-tstrsplit(QFT$StudyID, "_")

DonorInfo<-merge(PBMC, QFT, by="StudyID", all = TRUE)
DonorInfo$StudyID<-gsub("- plasma", "", DonorInfo$StudyID)
DonorInfo$StudyID<-gsub("-1", "", DonorInfo$StudyID)
DonorInfo$StudyID<-gsub("-0", "", DonorInfo$StudyID)
DonorInfo$Viability<-gsub("%" , "" , DonorInfo$Viability)
DonorInfo$Cells.Vial<-as.numeric(as.character(DonorInfo$Cells.Vial))
DonorInfo$QFT<-as.numeric(as.character(DonorInfo$QFT))
DonorInfo<-dplyr::rename(DonorInfo, Donor = StudyID)
```

```{r read in all flowjo data tables}
setwd("/Applications/Old Computer/Day Lab/Flow-Data/exported/")
filenames =list.files(pattern="*.csv")
for (i in 1:length(filenames)) 
    assign(filenames[i], read.csv(filenames[i]))
```

```{r reformatting functions}
clean_flowjo_output<-function(datatable){
    library(dplyr)
    datatable$Sample<-gsub("HD474", "HD454", datatable$Sample)
    datatable$Sample<-gsub("HD448", "HD488", datatable$Sample)
    datatable$Sample<-gsub("NK2341_TB_SM", "NK2341_TB_X", datatable$Sample)
    datatable$Sample<-gsub("001_", "", datatable$Sample)
    datatable$Sample<-gsub("1: |2: |3: |4: |5: |6: ", "", datatable$Sample)
    datatable$Sample<-gsub("XUN", "X_UN", datatable$Sample)
    datatable$Sample<-gsub("XPMA", "X_PMA", datatable$Sample)
    datatable$Sample<-gsub("XWCL", "X_WCL", datatable$Sample)
    datatable$Sample<-gsub("XPEP", "X_PEP", datatable$Sample)
    datatable$Sample<-gsub("XSEA", "X_SEA", datatable$Sample)
    datatable$Sample<-gsub("XSWAP", "X_SWAP", datatable$Sample)
    datatable$Sample<-gsub("_ ", "_", datatable$Sample)
    datatable$Sample<-gsub(" _", "_", datatable$Sample)
    datatable<-filter(datatable,!(Sample=="Mean"))%>%
        filter(!Sample=="StdDev")%>%
        filter(!Sample=="Sample")%>%
        filter(!Sample=="Sample")
    datatable[datatable=="¥"]<-NA
    datatable[datatable=="•"]<-NA
    datatable
    
}

splitter<-function(data,column,splitter,one=NULL,two=NULL,three=NULL,four=NULL){
    library(data.table)
    
    labels<-tstrsplit(data[,column], splitter)
    data[,one]<-labels[[1]]
    data[,two]<-labels[[2]]
    data[,three]<-labels[[3]]
    data[,four]<-labels[[4]]
    return(data)
}
#demo: HEL<-splitter(HEL, "StudyID", "-", one="StudyID", two="Visit", three="Iteration")

remove_samples<-function(datatable){
    library(dplyr)
    excluded_samples<-c("NK2126_HC_X_SEA_005.fcs", 
                        "NK2450_HC_SM_SEA_047.fcs" , 
                        "NK2402_LTBI_SM_SWAP_024.fcs",
                        "NK2342_TB_X_SWAP_006.fcs",
                        "NK2136_TB_X_WCL_003.fcs",
                        "NK2168_HC_SM_WCL_040.fcs",
                        "NK2421_LTBI_SM_PEP_010.fcs",
                        "NK2063_TB_X_SEA_005.fcs",
                        "NK2115_LTBI_X_PEP_010.fcs",
                        "NK2115_LTBI_X_WCL_009.fcs",
                        "NK2171_HC_X_WCL_009.fcs",
                        "NK2162_HC_X_SEA_023.fcs")
    datatable<-filter(datatable, !(Sample %in% excluded_samples))%>%
        filter(!(Donor == "NK2111"))
    datatable
}

class_change<-function(datatable){
    y<-dplyr::select(datatable, Sample, Donor, TB, SM, Stim)
    x<-dplyr::select(datatable, -Sample, -Donor, -TB, -SM, -Stim)
    for(i in 1:length(x)){x[[i]]<-as.numeric(as.character(x[[i]]))}
    df<-cbind(y, x)
}

```

```{r, reformat all data tables}
l<-list(CD4_Counts.csv, CD4_Cytokine.csv, CD4_MFI.csv, CD4_Positive.csv, CD4.csv, 
        CD8_Counts.csv, CD8_Cytokine.csv, GD_Counts.csv, GD_Cytokine.csv)
l<-lapply(l, function(x) clean_flowjo_output(x))
l<-lapply(l, function(x) splitter(x, "Sample", "_", one="Donor", two="TB", three="SM", four="Stim"))
l<-lapply(l, function(x) remove_samples(x))
l<-lapply(l, function(x) class_change(x))
for (i in 1:length(filenames)) {
    assign(filenames[i], data.frame(l[i]))}
```

```{r change colnames}
newnames<-names(CD8_Cytokine.csv)
names(CD4_Counts.csv)<-newnames[1:21]
names(CD8_Counts.csv)<-newnames
names(GD_Counts.csv)<-newnames
names(GD_Cytokine.csv)<-newnames
```

```{r update and re-organize count data}
library(dplyr)
CD4_Counts.csv<-mutate(CD4_Counts.csv,
    IFNg=  G_4_13_T + G_4_13_x + G_4_x_T + G_4_x_x + G_x_13_T + G_x_13_x + G_x_x_T + G_x_x_x,
    TNFa=  G_4_13_T + G_4_x_T + G_x_13_T + G_x_x_T + x_4_13_T + x_4_x_T + x_x_13_T + x_x_x_T,
    IL13=  G_4_13_T + G_4_13_x + G_x_13_T + G_x_13_x + x_4_13_T + x_4_13_x + x_x_13_T + x_x_13_x,
    IL4=   G_4_13_T + G_4_13_x + G_4_x_T + G_4_x_x + x_4_13_T + x_4_13_x + x_4_x_T + x_4_x_x,
    Total= G_4_13_T + G_4_x_T + G_x_13_T + G_4_13_x + x_4_13_T + G_4_x_x + G_x_13_x + x_4_x_T + x_x_13_T + G_x_x_T  + G_x_x_x + x_x_x_T +  x_4_13_x + x_4_x_x + x_x_13_x + x_x_x_x
)
xtracounts<-dplyr::select(CD4_Cytokine.csv, Sample, Cyt.Count, TH1.Count, TH1.2.Count, TH2.Count)%>%
    dplyr::rename(Cyt = Cyt.Count, TH1 = TH1.Count, TH2 = TH2.Count, TH1.2 = TH1.2.Count)

CD4_Counts.csv<-merge(CD4_Counts.csv, xtracounts, by = "Sample")
```

```{r create new combo cytokine variables}
library(dplyr)
filenames = c("CD4_Cytokine.csv", "CD8_Cytokine.csv", "GD_Cytokine.csv")
l<-list(CD4_Cytokine.csv, CD8_Cytokine.csv, GD_Cytokine.csv)
l<-lapply(l, function(x) dplyr::mutate(x, G_plus = G_4_13_x + G_4_x_x + G_x_13_x + G_x_x_x,
                   T_plus = x_4_13_T + x_4_x_T + x_x_13_T + x_x_x_T,
                   G_T_plus = G_4_x_T + G_x_13_T + G_x_x_T,
                   IL4_plus = G_4_x_T + G_4_x_x + x_4_x_T + x_4_x_x,
                   IL13_plus = G_x_13_T + G_x_13_x + x_x_13_T + x_x_13_x,
                   IL4_IL13_plus = G_4_13_x + x_4_13_T + x_4_13_x)
)

for (i in 1:length(filenames)) {
    assign(filenames[i], 
           data.frame(l[i]))}
```

```{r Cytokine MFI inclusion}
counts.ref<-CD4_Counts.csv
DF<-arrange(CD4_MFI.csv, Sample)
CD4_Counts.csv<-arrange(CD4_Counts.csv, Sample)
CD4_MFI.csv<-arrange(CD4_MFI.csv, Sample)

keynames<-colnames(counts.ref)[6:29]
for(key in keynames){
    remove<-subset(counts.ref, counts.ref[,key]<20)$Sample
    print(key)
    print(length(remove))
    DF[(DF$Sample %in% remove), grep(paste(key,"_",sep=""), names(DF))]<-NA
}

#for me
#for(key in keynames){
#    print(key)
#    test<-data.frame(cbind(CD4_Counts.csv[grep(key, names(CD4_Counts.csv))], 
#                           CD4_MFI.csv[grep(paste(key,"_",sep=""), names(CD4_MFI.csv))],
#                           DF[grep(paste(key,"_",sep=""), names(DF))]))
#    print(length(which(test[,1]<20 &! is.na(test[,2:5]))))
#    print(length(which(test[,1]<20 &! is.na(test[,6:9]))))
#}

CD4_MFI.csv<-DF
```

```{r subtract unstimulated from cyt freq tables}
#used to generate a list of character strings that are the names of the columns containing numeric data
numeric.only <- function(X,...){
      returnCols <- names(X)
      a<-sapply(X, is.numeric)
      print(returnCols[a == "TRUE"])
}

#takes a dataframe (v. important its a dataframe), splitvar is a character string of a column name
#colnms is a list of strings indicating which columns to subtract background from
#condition is a character string with the key to indicate what is being subtracted
background.subtract<-function(df, splitvar, keyvar, condition){
    df<-dplyr::arrange(df, df[,splitvar])
    dt<-split(df, df[, splitvar]) #generate a list of mini data frames for each level of splitvar
    #split --> lists in alphabetical order not by original key order
    #To solve this I arranged the original data frame in alphabetical order
    #can we instead arrange the split to match the original order

    colnms<-numeric.only(df)
    
    #for each column name in the list of column names
    for(col in colnms){
        #this is a check to make sure it goes through all the columns
        print(col) 
        #dt.r will make a list of length of dt where each item in the list is the new column for a particular donor
        dt.r<-lapply(dt, function(g)
        #take the values in each column and subtract out the value indicated by an "un" the stim column 
        (g[,col] - subset(g, g[,keyvar]==condition)[,col]))
        #unlist the list so you get a single column and insert it back into the original data frame
        df[,col]<-unlist(dt.r)
    }
    df
}

filenames = c("CD4_Cytokine.csv", "CD8_Cytokine.csv", "GD_Cytokine.csv")
l<-list(CD4_Cytokine.csv, CD8_Cytokine.csv, GD_Cytokine.csv)
l<-lapply(l, function(x) arrange(x, Donor))
l<-lapply(l, function(x) background.subtract(x, "Donor", "Stim", "UN"))
for (i in 1:length(filenames)) {
    assign(filenames[i], 
           data.frame(l[i]))}
CD4_Cytokine.csv[CD4_Cytokine.csv<0]<-0
CD8_Cytokine.csv[CD8_Cytokine.csv<0]<-0
GD_Cytokine.csv[GD_Cytokine.csv<0]<-0
```

```{r write files to "clean" directory}
setwd("/Applications/Old Computer/Day Lab/Flow-Data/clean/")
df.list<-list(CD4_Counts.csv, CD4_Cytokine.csv, CD4_MFI.csv, CD4_Positive.csv,
              CD4.csv, CD8_Counts.csv, CD8_Cytokine.csv, GD_Counts.csv,
              GD_Cytokine.csv)
dfnames<-list("CD4_Counts", "CD4_Cytokine", "CD4_MFI", "CD4_Positive",
              "CD4", "CD8_Counts", "CD8_Cytokine", "GD_Counts",
              "GD_Cytokine")
newfilenames<-paste(dfnames, "clean", date(), ".csv", sep="_")
#write.csv(df.list[1], file= newfilenames[1])
write.csv(CD4_Counts.csv, file = "CD4_Counts_clean.csv")
write.csv(CD4_Cytokine.csv, file = "CD4_Cytokine_clean.csv")
write.csv(CD4_MFI.csv, file = "CD4_MFI_clean.csv")
write.csv(CD4_Positive.csv, file = "CD4_Positive_clean.csv")
write.csv(CD4.csv, file = "CD4_clean.csv")
write.csv(CD8_Counts.csv, file = "CD8_Counts_clean.csv")
write.csv(CD8_Cytokine.csv, file = "CD8_Cytokine_clean.csv")
write.csv(GD_Counts.csv, file = "GD_Counts_clean.csv")
write.csv(GD_Cytokine.csv, file = "GD_Cytokine_clean.csv")
write.csv(DonorInfo, file = "ICS_Donor_Info_clean.csv")
```

