---
title: "ICS_master_processing"
author: "Taryn McLaughlin"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
master<-fread("/Applications/Old Computer/Day Lab/Flow-Data/Master-ICS.csv")
```

```{r, cache=TRUE}
library(dplyr)
master$Sample<-paste(master$donor, master$Stim, sep ="_")
master<-dplyr::select(master, -V1, -X, -donor, -FSC.A, -FSC.H, -FSC.W, -SSC.A, -SSC.W, -SSC.H, -Stim)
```

```{r Building Boolean for Total CD4 Lineage Markers}
samples<-split(master, master$Sample)

t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
boolean<-data.frame(bind_cols(l.col))
names(boolean)<-c("t_g_3_4", "t_g_3_x", "t_g_x_4", "t_g_x_x", 
                  "t_x_3_4", "t_x_3_x", "t_x_x_4", "t_x_x_x",
                  "x_g_3_4", "x_g_3_x", "x_g_x_4", "x_g_x_x",
                  "x_x_3_4", "x_x_3_x", "x_x_x_4", "x_x_x_x"
                  )
boolean$Sample<-names(x_x_x_x)
```

```{r tbet}
tbet<-filter(master, !is.na(Tbet_gate))
samples<-split(tbet, tbet$Sample)

G_4_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$Tbet_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
tbet<-data.frame(bind_cols(l.col))
names(tbet)<-c("G_4_13_T", "G_4_13_x", "G_4_x_T", "G_4_x_x",  
                "G_x_13_T", "G_x_13_x", "G_x_x_T", "G_x_x_x",
                  "x_4_13_T", "x_4_13_x", "x_4_x_T", "x_4_x_x",
                  "x_x_13_T", "x_x_13_x", "x_x_x_T", "x_x_x_x"
                  )
newnames<-paste("tbet", names(tbet), sep="_")
names(tbet)<-newnames
tbet$Sample<-names(x_x_x_x)
```

```{r gata3}
gata3<-filter(master, !is.na(GATA3_gate))
samples<-split(gata3, gata3$Sample)

G_4_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_4_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

G_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_4_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & !is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            !is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_T<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & !is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$IFNg_gate)  & is.na(g$IL4_gate) &
            is.na(g$IL13_gate) & is.na(g$TNFa_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
gata3<-data.frame(bind_cols(l.col))
names(gata3)<-c("G_4_13_T", "G_4_13_x", "G_4_x_T", "G_4_x_x",  
                "G_x_13_T", "G_x_13_x", "G_x_x_T", "G_x_x_x",
                  "x_4_13_T", "x_4_13_x", "x_4_x_T", "x_4_x_x",
                  "x_x_13_T", "x_x_13_x", "x_x_x_T", "x_x_x_x"
                  )
newnames<-paste("gata3", names(gata3), sep="_")
names(gata3)<-newnames
gata3$Sample<-names(x_x_x_x)
```


```{r TH1 phenotype}
TH1<-filter(master, !is.na(IFNg_gate) | !is.na(TNFa_gate) &
        is.na(IL4_gate) & is.na(IL13_gate))
samples<-split(TH1, TH1$Sample)

t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
TH1<-data.frame(bind_cols(l.col))
names(TH1)<-c("t_g_3_4", "t_g_3_x", "t_g_x_4", "t_g_x_x", 
                  "t_x_3_4", "t_x_3_x", "t_x_x_4", "t_x_x_x",
                  "x_g_3_4", "x_g_3_x", "x_g_x_4", "x_g_x_x",
                  "x_x_3_4", "x_x_3_x", "x_x_x_4", "x_x_x_x"
                  )
newnames<-paste("TH1", names(TH1), sep="_")
names(TH1)<-newnames
TH1$Sample<-names(x_x_x_x)
```

```{r TH2 phenotype}
TH2<-filter(master, is.na(IFNg_gate) | is.na(TNFa_gate) &
        !is.na(IL4_gate) & !is.na(IL13_gate))
samples<-split(TH2, TH2$Sample)

t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
TH2<-data.frame(bind_cols(l.col))
names(TH2)<-c("t_g_3_4", "t_g_3_x", "t_g_x_4", "t_g_x_x", 
                  "t_x_3_4", "t_x_3_x", "t_x_x_4", "t_x_x_x",
                  "x_g_3_4", "x_g_3_x", "x_g_x_4", "x_g_x_x",
                  "x_x_3_4", "x_x_3_x", "x_x_x_4", "x_x_x_x"
                  )
newnames<-paste("TH2", names(TH2), sep="_")
names(TH2)<-newnames
TH2$Sample<-names(x_x_x_x)
```

```{r TNF phenotype}
tnf<-filter(master, !is.na(TNFa_gate))
samples<-split(tnf, tnf$Sample)

t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
tnf<-data.frame(bind_cols(l.col))
names(tnf)<-c("t_g_3_4", "t_g_3_x", "t_g_x_4", "t_g_x_x", 
                  "t_x_3_4", "t_x_3_x", "t_x_x_4", "t_x_x_x",
                  "x_g_3_4", "x_g_3_x", "x_g_x_4", "x_g_x_x",
                  "x_x_3_4", "x_x_3_x", "x_x_x_4", "x_x_x_x"
                  )
newnames<-paste("tnfa", names(tnf), sep="_")
names(tnf)<-newnames
tnf$Sample<-names(x_x_x_x)
```

```{r IFN phenotype}
ifng<-filter(master, !is.na(IFNg_gate))
samples<-split(ifng, ifng$Sample)

t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

l.col<-lapply(ls(pattern="._._._."), function(x) get(x))
ifng<-data.frame(bind_cols(l.col))
names(ifng)<-c("t_g_3_4", "t_g_3_x", "t_g_x_4", "t_g_x_x", 
                  "t_x_3_4", "t_x_3_x", "t_x_x_4", "t_x_x_x",
                  "x_g_3_4", "x_g_3_x", "x_g_x_4", "x_g_x_x",
                  "x_x_3_4", "x_x_3_x", "x_x_x_4", "x_x_x_x"
                  )
newnames<-paste("ifng", names(ifng), sep="_")
names(ifng)<-newnames
ifng$Sample<-names(x_x_x_x)
```

```{r}
#total CD4s
boolean$Sample<-gsub("T3" , "3" , boolean$Sample)
boolean$Sample<-gsub("T8" , "8" , boolean$Sample)

#new cytokine data
cyt<-merge(tbet, gata3, by="Sample")
cyt$Sample<-gsub("T8" , "8" , cyt$Sample)
cyt$Sample<-gsub("T3" , "3" , cyt$Sample)


#phenotyping
pheno<-data.frame(merge(TH1, TH2, by="Sample"))
pheno2<-data.frame(merge(pheno, tnf, by="Sample"))
pheno<-data.frame(merge(pheno2, ifng, by="Sample"))
pheno$Sample<-gsub("T3" , "3" , pheno$Sample)
pheno$Sample<-gsub("T8" , "8" , pheno$Sample)
```



```{r}
setwd("/Applications/Old Computer/Day Lab/Flow-Data/exported/")
#write.csv(boolean, "CD4_new.csv")
write.csv(cyt, "CD4_cytokine_new.csv")
#write.csv(pheno, "CD4_phenotype_new.csv")
```


