---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE )
```

```{r read in all flowjo data tables}
#change working directory to wherever the exported files are
setwd("/Applications/Old Computer/Day Lab/Flow-Data/exported/")
#find all the csv filenames in that directory and put them in a list
filenames =list.files(pattern="*.csv")
#for each name in that list, assign it to the output of read.csv of that name
#aka read in each file by it's name
for (i in 1:length(filenames)) 
    assign(filenames[i], read.csv(filenames[i]))
```

```{r source functions used in this script}
source("/Users/tarynam/Desktop/Miscellaneous-Scripts/tryna function.R")
source("/Users/tarynam/Desktop/Miscellaneous-Scripts/ICS-cleaning-functions.R")
```

```{r ICS compass}
ICS_Compass_scores_complete.csv<-changeTB(ICS_Compass_scores_complete.csv)
ICS_Compass_scores_complete.csv<-changeHD(ICS_Compass_scores_complete.csv)
ICS_Compass_scores_complete.csv<-fix.names(ICS_Compass_scores_complete.csv)
ICS_Compass_scores_complete.csv<-remove_samples(ICS_Compass_scores_complete.csv)
ICS_Compass_scores_complete.csv<-remove_donors(ICS_Compass_scores_complete.csv)
write.csv(ICS_Compass_scores_complete.csv,
          "/Applications/Old Computer/Day Lab/Flow-Data/clean/ICS_compass_complete_clean.csv"
)
```

```{r, reformat all data tables}
#this puts all the dataframes into a list 
#then applies each function over the dataframes in the list
#and assigns the output of that to the same named list
#so at every step the list of dataframes gets updated based on the function output 

l<-list(CD4_Counts.csv, CD4_Cytokine.csv, CD4_MFI.csv, CD4_new.csv,
        CD4_phenotype_new.csv, CD4_phenotype.csv, CD4.csv, 
        CD8_Counts.csv, CD8_Cytokine.csv, 
        GD_Counts.csv, GD_Cytokine.csv
        )
l<-lapply(l, function(x) clean_flowjo_output(x))
l<-lapply(l, function(x) splitter(x, "Sample", "_", one="Donor", two="TB", three="SM", four="Stim"))
l<-lapply(l, function(x) fix.names(x))
l<-lapply(l, function(x) remove_samples(x))
l<-lapply(l, function(x) remove_donors(x))
l<-lapply(l, function(x) class_change(x))
l<-lapply(l, function(x) changeTB(x))
l<-lapply(l, function(x) changeHD(x))

#then we use the assign function to extract each data frame from the list and assign it to the filename
#associated with it from the beginning
#this only works because the list of dataframes is arranged in the same order as the list filenames 
for (i in 1:length(filenames)) {
   assign(filenames[i], data.frame(l[i]))}
```

```{r change colnames}
#I only bothered to change the names in flowjo for CD4/8 Cytokine exports so the rest are ugly
newnames<-names(CD8_Cytokine.csv)
#luckily the columns are in the same order so I can just take the names from one of those 
names(CD4_Counts.csv)<-newnames[1:21]
#and give it to all the counts tables
names(CD8_Counts.csv)<-newnames
names(GD_Counts.csv)<-newnames
names(GD_Cytokine.csv)<-newnames

CD4_Cytokine.csv <- dplyr::rename(CD4_Cytokine.csv, TH1.Freq = Th1.Freq)
```

```{r update and re-organize count data}
library(dplyr)
#again an oversight but I didn't export total counts for CD4 so I have to make them to match 
#CD8 and GD counts tables
#mutate just means make a new variable 
CD4_Counts.csv<-mutate(CD4_Counts.csv,
    #These all follow the same format
    #IFNg is the new variable. it gets assign the row sum of all the columns that have a G in the name
    IFNg=  rowSums(CD4_Counts.csv[,grep("G", names(CD4_Counts.csv))]),
    TNFa=  rowSums(CD4_Counts.csv[,grep("_T", names(CD4_Counts.csv))]),
    IL13=  rowSums(CD4_Counts.csv[,grep("13", names(CD4_Counts.csv))]),
    IL4=   rowSums(CD4_Counts.csv[,grep("4", names(CD4_Counts.csv))])
)
#pulls the columns with counts from the CD4_Cytokine export
xtracounts<-dplyr::select(CD4_Cytokine.csv, Sample, Cyt.Count, TH1.Count, TH1.2.Count, TH2.Count)%>%
    dplyr::rename(Cyt = Cyt.Count, TH1 = TH1.Count, TH2 = TH2.Count, TH1.2 = TH1.2.Count)
#and sticks them in this table
CD4_Counts.csv<-merge(CD4_Counts.csv, xtracounts, by = "Sample")

#creating variables for TH1 and TH2 that include co-prouducing cells
CD4_Counts.csv$TH1.Total<-(CD4_Counts.csv$TH1 + CD4_Counts.csv$TH1.2)
CD4_Counts.csv$TH2.Total<-(CD4_Counts.csv$TH2 + CD4_Counts.csv$TH1.2)

#Creating a total counts column
CD4_Counts.csv$Total<-CD4_Counts.csv$x_x_x_x + CD4_Counts.csv$Cyt

#then remove them from the other table
CD4_Cytokine.csv<-dplyr::select(CD4_Cytokine.csv, -Cyt.Count, -TH1.Count, -TH1.2.Count, -TH2.Count)
```

```{r update and organize cytokine variables}
#If you want to know the double producers without considering the opposite TH cytokines
library(dplyr)
CD4_Cytokine.csv<-dplyr::mutate(CD4_Cytokine.csv, G_T = G_4_x_T + G_x_13_T + G_x_x_T,
                   IL4_IL13 = G_4_13_x + x_4_13_T + x_4_13_x,
                   TH1.Total = TH1.Freq + TH1.2.Freq,
                   TH2.Total = TH2.Freq + TH1.2.Freq
                   )
```

```{r update and merge phenotype data}
CD4<-merge(CD4.csv, CD4_new.csv, by=c("Sample","Donor","TB","SM","Stim" ), all=TRUE)
CD4_phenotype<-merge(CD4_phenotype.csv, CD4_phenotype_new.csv, by=c("Sample","Donor","TB","SM","Stim" ), all=TRUE)
```

```{r create new combo variables from exported boolean phenotype}
CD4<-mutate(CD4,
      #These all follow the same format
       #IFNg is the new variable. it gets assign the row sum of all the columns that have a G in the name
       TbetCXCR3=  rowSums(CD4[,grep("t_._3_.", names(CD4))]),
       TbetCCR4=  rowSums(CD4[,grep("t_._._4", names(CD4))]),
       GATA3CXCR3=  rowSums(CD4[,grep("._g_3_.", names(CD4))]),
       GATA3CCR4=  rowSums(CD4[,grep("._g_._4", names(CD4))]),
       CXCR3.Tbetprop = TbetCXCR3/Tbet,
       CCR4.Tbetprop = TbetCCR4/Tbet,
       CXCR3.GATA3prop= GATA3CXCR3/GATA3,
       CCR4.GATA3prop= GATA3CCR4/GATA3
)

CD4_phenotype<-mutate(CD4_phenotype,
      #These all follow the same format
      ifng_Tbet=  rowSums(CD4_phenotype[,grep("ifng_t_._._.", names(CD4_phenotype))]),
      ifng_GATA3=  rowSums(CD4_phenotype[,grep("ifng_._g_._.", names(CD4_phenotype))]),
      ifng_CCR4=  rowSums(CD4_phenotype[,grep("ifng_._._._4", names(CD4_phenotype))]),
      ifng_CXCR3=  rowSums(CD4_phenotype[,grep("ifng_._._3_.", names(CD4_phenotype))]),
      tnfa_Tbet=  rowSums(CD4_phenotype[,grep("tnfa_t_._._.", names(CD4_phenotype))]),
      tnfa_GATA3=  rowSums(CD4_phenotype[,grep("tnfa_._g_._.", names(CD4_phenotype))]),
      tnfa_CCR4=  rowSums(CD4_phenotype[,grep("tnfa_._._._4", names(CD4_phenotype))]),
      tnfa_CXCR3=  rowSums(CD4_phenotype[,grep("tnfa_._._3_.", names(CD4_phenotype))]),      
     
      TH1_TbetCXCR3=  rowSums(CD4_phenotype[,grep("TH1_t_._3_.", names(CD4_phenotype))]),
      TH1_TbetCCR4=  rowSums(CD4_phenotype[,grep("TH1_t_._._4", names(CD4_phenotype))]),
      TH1_GATA3CXCR3=  rowSums(CD4_phenotype[,grep("TH1_._g_3_.", names(CD4_phenotype))]),
      TH1_GATA3CCR4=  rowSums(CD4_phenotype[,grep("TH1_._g_._4", names(CD4_phenotype))]),
      TH2_TbetCXCR3=  rowSums(CD4_phenotype[,grep("TH2_t_._3_.", names(CD4_phenotype))]),
      TH2_TbetCCR4=  rowSums(CD4_phenotype[,grep("TH2_t_._._4", names(CD4_phenotype))]),
      TH2_GATA3CXCR3=  rowSums(CD4_phenotype[,grep("TH2_._g_3_.", names(CD4_phenotype))]),
      TH2_GATA3CCR4=  rowSums(CD4_phenotype[,grep("TH2_._g_._4", names(CD4_phenotype))]),
      ifng_TbetCXCR3=  rowSums(CD4_phenotype[,grep("ifng_t_._3_.", names(CD4_phenotype))]),
      ifng_TbetCCR4=  rowSums(CD4_phenotype[,grep("ifng_t_._._4", names(CD4_phenotype))]),
      ifng_GATA3CXCR3=  rowSums(CD4_phenotype[,grep("ifng_._g_3_.", names(CD4_phenotype))]),
      ifng_GATA3CCR4=  rowSums(CD4_phenotype[,grep("ifng_._g_._4", names(CD4_phenotype))]),
      tnfa_TbetCXCR3=  rowSums(CD4_phenotype[,grep("tnfa_t_._3_.", names(CD4_phenotype))]),
      tnfa_TbetCCR4=  rowSums(CD4_phenotype[,grep("tnfa_t_._._4", names(CD4_phenotype))]),
      tnfa_GATA3CXCR3=  rowSums(CD4_phenotype[,grep("tnfa_._g_3_.", names(CD4_phenotype))]),
      tnfa_GATA3CCR4=  rowSums(CD4_phenotype[,grep("tnfa_._g_._4", names(CD4_phenotype))]),
      
       TH1_CXCR3.Tbetprop = TH1_TbetCXCR3/TH1_Tbet,
       TH1_CCR4.Tbetprop = TH1_TbetCCR4/TH1_Tbet,
       TH1_CXCR3.GATA3prop= TH1_GATA3CXCR3/TH1_GATA3,
       TH1_CCR4.GATA3prop= TH1_GATA3CCR4/TH1_GATA3,
      
       TH2_CXCR3.Tbetprop = TH2_TbetCXCR3/TH2_Tbet,
       TH2_CCR4.Tbetprop = TH2_TbetCCR4/TH2_Tbet,
       TH2_CXCR3.GATA3prop= TH2_GATA3CXCR3/TH2_GATA3,
       TH2_CCR4.GATA3prop= TH2_GATA3CCR4/TH2_GATA3,
      
       ifng_CXCR3.Tbetprop = ifng_TbetCXCR3/ifng_Tbet,
       ifng_CCR4.Tbetprop = ifng_TbetCCR4/ifng_Tbet,
       ifng_CXCR3.GATA3prop= ifng_GATA3CXCR3/ifng_GATA3,
       ifng_CCR4.GATA3prop= ifng_GATA3CCR4/ifng_GATA3,
             
       tnfa_CXCR3.Tbetprop = tnfa_TbetCXCR3/tnfa_Tbet,
       tnfa_CCR4.Tbetprop = tnfa_TbetCCR4/tnfa_Tbet,
       tnfa_CXCR3.GATA3prop= tnfa_GATA3CXCR3/tnfa_GATA3,
       tnfa_CCR4.GATA3prop= tnfa_GATA3CCR4/tnfa_GATA3
)


```

```{r Cytokine MFI inclusion}
#duplicate and rename the counts table so you don't fuck it up but can still use it
counts.ref<-CD4_Counts.csv
#arrange tables by Sample so the rows match up
counts.ref<-arrange(counts.ref, Sample)
CD4_MFI.csv<-arrange(CD4_MFI.csv, Sample)
#duplicate the mfi table again so you can change it but preserve the original just in case
DF<-arrange(CD4_MFI.csv, Sample)

#This is explained in detail in a separate script named "remove-samples-using-key.R"
keynames<-colnames(counts.ref)[6:29]
for(key in keynames){
    remove<-subset(counts.ref, counts.ref[,key]<20)$Sample
    print(key)
    print(length(remove))
    DF[(DF$Sample %in% remove), grep(paste(key,"_",sep=""), names(DF))]<-NA
}

#for me to test but doesn't work if you are actively working with the code. Only works if you just run the whole script. also documented in the same script as above
for(key in keynames){
    print(key)
    test<-data.frame(cbind(counts.ref[grep(key, names(counts.ref))], 
                           CD4_MFI.csv[grep(paste(key,"_",sep=""), names(CD4_MFI.csv))],
                           DF[grep(paste(key,"_",sep=""), names(DF))]))
    print(length(which(test[,1]<19 &! is.na(test[,2:5]))))
    print(length(which(test[,1]<19 &! is.na(test[,6:9]))))
}

#now that we have checked, we can assign it back to the original name
CD4_MFI.csv<-DF
```

```{r subtract unstimulated from cyt freq tables}
#the documentation for the background.subtract function is in a script in the miscellaneous folder
#just subtracts the value of the unstim from the value of the stim by donor
filenames = c("CD4_Cytokine.csv", "CD8_Cytokine.csv", "GD_Cytokine.csv")
l<-list(CD4_Cytokine.csv, CD8_Cytokine.csv, GD_Cytokine.csv)
l<-lapply(l, function(x) arrange(x, Donor))
l<-lapply(l, function(x) background.subtract(x, "Donor", "Stim", "UN"))
for (i in 1:length(filenames)) {
    assign(filenames[i], 
           data.frame(l[i]))}
#sets all negative values to zero
CD4_Cytokine.csv[CD4_Cytokine.csv<0]<-0
CD8_Cytokine.csv[CD8_Cytokine.csv<0]<-0
GD_Cytokine.csv[GD_Cytokine.csv<0]<-0
```

```{r remove specific CD8/GD tables}
pbmc<-read.csv("/Applications/Old Computer/Day Lab/Flow-Data/clean/ICS_DonorInfo_clean.csv")
cd8.remove<-filter(pbmc, grepl("CD8", Excluded))$Donor
CD8_Counts.csv<-filter(CD8_Counts.csv, !(Donor %in% cd8.remove))
CD8_Cytokine.csv<-filter(CD8_Cytokine.csv, !(Donor %in% cd8.remove))

gd.remove<-filter(pbmc, grepl("CD4-", Excluded))$Donor
GD_Counts.csv<-filter(GD_Counts.csv, !(Donor %in% cd8.remove))
GD_Cytokine.csv<-filter(GD_Cytokine.csv, !(Donor %in% cd8.remove))

```

```{r write files to "clean" directory}
setwd("/Applications/Old Computer/Day Lab/Flow-Data/clean/")
write.csv(CD4_Counts.csv, file = "ICS_CD4_Counts_clean.csv")
write.csv(CD4_Cytokine.csv, file = "ICS_CD4_Cytokine_clean.csv")
write.csv(CD4_MFI.csv, file = "ICS_CD4_MFI_clean.csv")
write.csv(CD4_phenotype, file = "ICS_CD4_phenotype_clean.csv")
write.csv(CD4, file = "ICS_CD4_clean.csv")
write.csv(CD8_Counts.csv, file = "ICS_CD8_Counts_clean.csv")
write.csv(CD8_Cytokine.csv, file = "ICS_CD8_Cytokine_clean.csv")
write.csv(GD_Counts.csv, file = "ICS_GD_Counts_clean.csv")
write.csv(GD_Cytokine.csv, file = "ICS_GD_Cytokine_clean.csv")
```

