---
title: "Untitled"
author: "Taryn McLaughlin"
date: "2/24/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, cache=TRUE}
library(data.table)
master<-fread("/Applications/Old Computer/Day Lab/Flow-Data/Master-OG2.csv")
```

```{r libraries, echo=FALSE, message=FALSE}
library(ggplot2)
library(ggpubr)
library(GGally)
library(knitr)
library(gbm)
library(dplyr)
```

```{r functions for processing}
include.gate<-function(data, column){
    include <- dplyr::filter(data, !is.na(data[,column]))
    include
}

exclude.gate<-function(data, column){
    exclude <- dplyr::filter(data, is.na(data[,column]))
    exclude
}

proc.count<-function(data, column){
    count<-length(which(!is.na(data[,column])))
    count
}

proc.freq<-function(data, column){ #mimics frequency of parent gate
    numerator<-length(which(!is.na(data[,column])))
    denominator<- length(data[,column])
    freq<-(numerator/denominator)*100
    freq
}

proc.MFI<-function(data, column){
    MFI<-median(data[,column])
    MFI
}
```

```{r smaller tables, cache=TRUE}
CD3<-dplyr::filter(master, !is.na(CD3_gate))
CD4<-dplyr::filter(master, !is.na(CD3_gate), !is.na(CD4_gate))%>%
    dplyr::filter(is.na(CD8_gate), is.na(GD_gate))
CD8<-dplyr::filter(master, !is.na(CD3_gate), !is.na(CD8_gate))%>%
    dplyr::filter(is.na(CD4_gate), is.na(GD_gate))
gd<-dplyr::filter(master, !is.na(CD3_gate), !is.na(GD_gate))
GD<-dplyr::filter(master, !is.na(CD3_gate), !is.na(GD_gate))%>%
    dplyr::filter(is.na(CD8_gate), is.na(CD4_gate))

CD3_OG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(OG_gate))
CD4_OG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(CD4_gate), !is.na(OG_gate))%>%
    dplyr::filter(is.na(CD8_gate), is.na(GD_gate))
CD4_noOG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(CD4_gate))%>%
    dplyr::filter(is.na(CD8_gate), is.na(GD_gate), is.na(OG_gate))
CD8_OG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(CD8_gate), !is.na(OG_gate))%>%
    dplyr::filter(is.na(CD4_gate), is.na(GD_gate))
gd_OG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(GD_gate), !is.na(OG_gate))
GD_OG<-dplyr::filter(master, !is.na(CD3_gate), !is.na(GD_gate), !is.na(OG_gate))%>%
    dplyr::filter(is.na(CD8_gate), is.na(CD4_gate))
```

CD4s
```{r CD4 summary stats, cache=TRUE}
df<-CD4
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_bulk_summary<-data.frame(cbind(singles, cytokine, boolean))
CD4_bulk_summary$Sample<-row.names(CD4_bulk_summary)
```

```{r Proliferating CD4s}
df<-CD4_OG
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG_summary<-data.frame(cbind(singles, cytokine, boolean))
CD4_OG_summary$Sample<-row.names(CD4_OG_summary)
```

```{r Non-Proliferating CD4s}
df<-CD4_noOG
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_noOG_summary<-data.frame(cbind(singles, cytokine, boolean))
CD4_noOG_summary$Sample<-row.names(CD4_noOG_summary)
```

```{r Proliferating CD4s TH1 producing}
df<-filter(CD4_OG, !is.na(TNFa_gate) | !is.na(IFNg_gate))
df<-filter(df, is.na(IL4_gate))
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG.TH1_summary<-cbind(singles, cytokine, boolean)
CD4_OG.TH1_summary$Sample<-row.names(CD4_OG.TH1_summary)
```

```{r Proliferating CD4s GT producing}
df<-filter(CD4_OG, !is.na(TNFa_gate) & !is.na(IFNg_gate) & is.na(IL4_gate))
df<-filter(df, is.na(IL4_gate))
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG.GT_summary<-cbind(singles, cytokine, boolean)
CD4_OG.GT_summary$Sample<-row.names(CD4_OG.GT_summary)
```

```{r Proliferating CD4s TNFa producing}
df<-filter(CD4_OG, !is.na(CD4_OG$TNFa_gate))
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG.TNFa_summary<-cbind(singles, cytokine, boolean)
CD4_OG.TNFa_summary$Sample<-row.names(CD4_OG.TNFa_summary)
```

```{r Proliferating CD4s IFNg producing}
df<-filter(CD4_OG, !is.na(CD4_OG$IFNg_gate))
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG.IFNg_summary<-cbind(singles, cytokine, boolean)
CD4_OG.IFNg_summary$Sample<-row.names(CD4_OG.IFNg_summary)
```

```{r Proliferating CD4s IL4 producing}
df<-filter(CD4_OG, is.na(TNFa_gate) & is.na(IFNg_gate & !is.na(IL4_gate)))
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD4_OG.IL4_summary<-cbind(singles, cytokine, boolean)
CD4_OG.IL4_summary$Sample<-row.names(CD4_OG.IL4_summary)
```

CD8s
```{r CD8 summary stats, cache=TRUE}
df<-CD8
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD8_bulk_summary<-cbind(singles, cytokine, boolean)
CD8_bulk_summary$Sample<-row.names(CD8_bulk_summary)
```

```{r Proliferating CD8s }
df<-CD8_OG
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD8_OG_summary<-cbind(singles, cytokine, boolean)
CD8_OG_summary$Sample<-row.names(CD8_OG_summary)
```

Gamma Deltas defined without considering CD4 and CD8
```{r gd summary stats, cache=TRUE}
df<-gd
samples<-split(df, list(df$donor, df$Stim))
CD8_freq<-sapply(samples, function(g) proc.freq(g, "CD8_gate"))
CD4_freq<-sapply(samples, function(g) proc.freq(g, "CD4_gate"))
GD_freq<-sapply(samples, function(g) proc.freq(g, "GD_gate"))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(CD8_freq, CD4_freq, GD_freq, IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

#Figuring out CD4/CD8
CD4_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

CD4_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cd<-data.frame(cbind(CD4_CD8, CD4_x, x_CD8, x_x))

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
gd_bulk_summary<-cbind(cd, singles, cytokine, boolean)
gd_bulk_summary$Sample<-row.names(gd_bulk_summary)
```

```{r Proliferating gds }
df<-gd_OG
samples<-split(df, list(df$donor, df$Stim))
CD8_freq<-sapply(samples, function(g) proc.freq(g, "CD8_gate"))
CD4_freq<-sapply(samples, function(g) proc.freq(g, "CD4_gate"))
GD_freq<-sapply(samples, function(g) proc.freq(g, "GD_gate"))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(CD8_freq, CD4_freq, GD_freq, IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

#Figuring out CD4/CD8
CD4_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

CD4_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cd<-data.frame(cbind(CD4_CD8, CD4_x, x_CD8, x_x))


##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
gd_OG_summary<-cbind(cd, singles, cytokine, boolean)
gd_OG_summary$Sample<-row.names(gd_OG_summary)
```

Strict Gamma Deltas
```{r GD summary stats, cache=TRUE}
df<-GD
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
GD_bulk_summary<-cbind(singles, cytokine, boolean)
GD_bulk_summary$Sample<-row.names(GD_bulk_summary)
```

```{r Proliferating GDs }
df<-GD_OG
samples<-split(df, list(df$donor, df$Stim))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
GD_OG_summary<-cbind(singles, cytokine, boolean)
GD_OG_summary$Sample<-row.names(GD_OG_summary)
```

CD3 
```{r CD3 summary stats, cache=TRUE}
df<-CD3
samples<-split(df, list(df$donor, df$Stim))
CD8_freq<-sapply(samples, function(g) proc.freq(g, "CD8_gate"))
CD4_freq<-sapply(samples, function(g) proc.freq(g, "CD4_gate"))
GD_freq<-sapply(samples, function(g) proc.freq(g, "GD_gate"))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(CD8_freq, CD4_freq, GD_freq, IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

#Figuring out CD4/CD8
CD4_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

CD4_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cd<-data.frame(cbind(CD4_CD8, CD4_x, x_CD8, x_x))


##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD3_bulk_summary<-cbind(cd, singles, cytokine, boolean)
CD3_bulk_summary$Sample<-row.names(CD3_bulk_summary)
```

```{r Proliferating CD3s}
df<-CD3_OG
samples<-split(df, list(df$donor, df$Stim))
CD8_freq<-sapply(samples, function(g) proc.freq(g, "CD8_gate"))
CD4_freq<-sapply(samples, function(g) proc.freq(g, "CD4_gate"))
GD_freq<-sapply(samples, function(g) proc.freq(g, "GD_gate"))
IFNg_freq<-sapply(samples, function(g) proc.freq(g, "IFNg_gate"))
TNFa_freq<-sapply(samples, function(g) proc.freq(g, "TNFa_gate"))
IL4_freq<-sapply(samples, function(g) proc.freq(g, "IL4_gate"))
OG_freq<-sapply(samples, function(g) proc.freq(g, "OG_gate"))
GATA3_freq<-sapply(samples, function(g) proc.freq(g, "GATA3_gate"))
Tbet_freq<-sapply(samples, function(g) proc.freq(g, "Tbet_gate"))
CCR4_freq<-sapply(samples, function(g) proc.freq(g, "CCR4_gate"))
CXCR3_freq<-sapply(samples, function(g) proc.freq(g, "CXCR3_gate"))
singles<-cbind(CD8_freq, CD4_freq, GD_freq, IFNg_freq, TNFa_freq, IL4_freq, OG_freq, GATA3_freq, Tbet_freq, CCR4_freq, CXCR3_freq)

#Figuring out CD4/CD8
CD4_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

CD4_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_CD8<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & !is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$CD4_gate)  & is.na(g$CD8_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cd<-data.frame(cbind(CD4_CD8, CD4_x, x_CD8, x_x))

##Cytokines
T_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

T_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_G_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & !is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            !is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            is.na(g$TNFa_gate)  & is.na(g$IFNg_gate) &
            is.na(g$IL4_gate)
            ))
    denominator<- length(g$TNFa_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

cytokine<-data.frame(cbind(T_G_4, T_G_x, T_x_4, T_x_x, 
                  x_G_4, x_G_x, x_x_4, x_x_x))

#Boolean Markers
t_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

t_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
            !is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_g_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  & !is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_3_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
            !is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_4<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) & !is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

x_x_x_x<-sapply(samples, function(g){
        numerator<-length(which(
             is.na(g$Tbet_gate)  &  is.na(g$GATA3_gate) &
             is.na(g$CXCR3_gate) &  is.na(g$CCR4_gate)
            ))
    denominator<- length(g$GATA3_gate)
    freq<-(numerator/denominator)*100
    freq
}
)

boolean<-data.frame(cbind(t_g_3_4, t_g_3_x, t_g_x_4, t_g_x_x, 
                  t_x_3_4, t_x_3_x, t_x_x_4, t_x_x_x,
                  x_g_3_4, x_g_3_x, x_g_x_4, x_g_x_x,
                  x_x_3_4, x_x_3_x, x_x_x_4, x_x_x_x
                  ))
CD3_OG_summary<-cbind(cd, singles, cytokine, boolean)
CD3_OG_summary$Sample<-row.names(CD3_OG_summary)
```

Counts
```{r Count stats, cache=TRUE}
df<-CD4
samples<-split(df, list(df$donor, df$Stim))
CD4_count<-sapply(samples, function(g) proc.count(g, "OG_gate"))
CD4_total<-sapply(samples, function(g) proc.count(g, "CD4_gate"))
CD4_neg<-(CD4_total-CD4_count)

df<-CD8
samples<-split(df, list(df$donor, df$Stim))
CD8_count<-sapply(samples, function(g) proc.count(g, "OG_gate"))
CD8_total<-sapply(samples, function(g) proc.count(g, "CD8_gate"))
CD8_neg<-(CD8_total-CD8_count)

df<-GD
samples<-split(df, list(df$donor, df$Stim))
GD_count<-sapply(samples, function(g) proc.count(g, "OG_gate"))
GD_total<-sapply(samples, function(g) proc.count(g, "GD_gate"))
GD_neg<-(GD_total-GD_count)

df<-CD3
samples<-split(df, list(df$donor, df$Stim))
CD3_count<-sapply(samples, function(g) proc.count(g, "OG_gate"))
CD3_total<-sapply(samples, function(g) proc.count(g, "CD3_gate"))
CD3_neg<-(CD3_total-CD3_count)

counts<-data.frame(cbind(CD3_count, CD3_neg, CD4_count, CD4_neg, CD8_count, CD8_neg, GD_count, GD_neg))
counts$Sample<-row.names(counts)
```

```{r write files}
setwd("/Applications/Old Computer/Day Lab/Flow-Data/exported")
write.csv(CD4_noOG_summary, "OG_CD4_noOG_summary.csv")

#write.csv(CD3, "OG_CD3_total.csv")
#write.csv(CD4, "OG_CD4_total.csv")
#write.csv(CD8, "OG_CD8_total.csv")
#write.csv(GD, "OG_GD_total.csv")

write.csv(CD3_bulk_summary, "OG_CD3_bulk_summary.csv")
write.csv(CD3_OG_summary, "OG_CD3_OG_summary.csv")

write.csv(CD4_bulk_summary, "OG_CD4_bulk_summary.csv")
write.csv(CD4_OG_summary, "OG_CD4_OG_summary.csv")
write.csv(CD4_OG.GT_summary, "OG_CD4_OG.GT_summary.csv")
write.csv(CD4_OG.IL4_summary, "OG_CD4_OG.IL4_summary.csv")
write.csv(CD4_OG.TH1_summary, "OG_CD4_OG.TH1_summary.csv")
write.csv(CD4_OG.TNFa_summary, "OG_CD4_OG.TNFa_summary.csv")
write.csv(CD4_OG.IFNg_summary, "OG_CD4_OG.IFNg_summary.csv")


write.csv(CD8_bulk_summary, "OG_CD8_bulk_summary.csv")
write.csv(CD8_OG_summary, "OG_CD8_OG_summary.csv")

write.csv(gd_bulk_summary, "OG_gd_bulk_summary.csv")
write.csv(GD_bulk_summary, "OG_GD_bulk_summary.csv")
write.csv(gd_OG_summary, "OG_gd_OG_summary.csv")
write.csv(GD_OG_summary, "OG_GD_OG_summary.csv")

write.csv(counts, "OG_counts_summary.csv")
```



